import type { Metadata } from 'next';
import { Inter, Inter_Tight, Annie_Use_Your_Telescope } from 'next/font/google';
import './styles/globals.css';
import { cn } from '@/lib/utils';


const fontFamilyBody = Inter({
    variable: '--font-family-body',
    subsets: ['latin']
});

const fontFamilyHeading = Inter_Tight({
    variable: '--font-family-heading',
    subsets: ['latin']
});

const fontFamilyDisplay = Annie_Use_Your_Telescope({
    variable: '--font-family-display',
    subsets: ['latin'],
    weight: '400'
});


export const metadata: Metadata = {
    title: 'Tripni',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn(
                fontFamilyBody.variable,
                fontFamilyHeading.variable,
                fontFamilyDisplay.variable,
            )}
        >
            <body>
                <main>
                    {children}
                </main>
            </body>
        </html>
    );
}